spring:
  application:
    name: xianyu-server
  cloud:
    nacos:
      config:
        server-addr: 124.71.181.12:8848
        file-extension: yaml
  config:
    import:
    - optional:nacos:xianyu-server.yaml