spring:
  application:
    name: xianyu-server
  datasource:
    url: jdbc:postgresql://124.71.181.12:5432/xianyu
    username: postgres
    password: highgo@123
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 开启druid监控 暂时 不好用 ，可能是spring boot3 与druid适配有问题，
      # GitHub有好多人有问题，换成druid-start-3-也不好使
      stat-view-servlet:
        enabled: false
        login-password: xianyu
        login-username: xianyu
        url-pattern: /druid/*
  liquibase:
    enabled: false

server:
  port: 8088